# Site settings
title: garyfeng.github.io
email: gary.feng@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Site Description Goes Here.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: garyfeng2
github_username:  garyfeng
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
